### ISSUE TITLE
Soma update command

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#110]
Introducing `soma-list.toml` support and some edge cases may cause some unexpected and unwanted behaviors like:

- Problem renamed after update (during build)
- Problem removed after update (during build)
- Large local repository (or mounted nfs) is copied every build

By separating update command from build command, we can address this problem.

## Expected command
- `soma update`
  Updates all repositories
- `soma update [repository_name]`
  Updates the specified repository

**Comment by Qwaz** [comment]
This was handled in #120. The difference between the issue and the actual implementation is as follows.

* Updating all repositories is not implemented. (yet?)
* Large file handling is not addressed.
* If a problem is removed but there exists an image from the problem, update command is rejected.
