### ISSUE TITLE
Multiple problems in one repository

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#36]
Current implementation assumes that a repository contains one problem.

Support one-repository-multi-problem scenario.

- [x] separate repository and problem
- [x] `soma_list.toml` parsing
- [x] docker build support for multi-problem scenario

**Comment by Qwaz** [comment]
I think this should be included in 0.1.0 because it is expected to introduce a lot of incompatibility to our API.

**Comment by KSAlpha** [comment]
Also consider moving some structs like `Manifest` and `SolidManifest` in `soma::repo` to `soma::repo::problem`.
