### ISSUE TITLE
Sanitize names

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#53]
Current implementations do not require any conditions for a valid name. To prevent some errors which can happen by names, string sanitization is required.

- [x] Repository Name
- [x] Problem Name
- [x] Soma username
- [x] ...

**Comment by Qwaz** [comment]
Related #44

**Comment by Qwaz** [comment]
Idea: Introduce a new struct `SanitizedString` which is a thin wrapper around `String`. It only allows a subset of string which is both a valid path and a valid docker identifier.
