### ISSUE TITLE
Change local repository prefix from # to other character

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#58]
`#` may require escaping in some environment, resulting in bad user experience.

Some candidates are: `%`. `+`. `_`. `.`, `:`, `-`, and maybe `~`

https://github.com/PLUS-POSTECH/soma/pull/55#discussion_r245466544

**Comment by Qwaz** [comment]
What about using @?

**Comment by KSAlpha** [comment]
I think it's fine. However, removing the indentifier may also be the option
