### ISSUE TITLE
Refactor `RepositoryIndex`

### ISSUE THREAD

**Issue by Qwaz** [PLUS-POSTECH/soma#71]
- [ ] Use [RAII pattern](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) to handle mutable index
- [ ] Encapsulize key-value handling
- [ ] Only one mutable index at a time

**Comment by KSAlpha** [comment]
Consider hardening repository existence check (https://github.com/PLUS-POSTECH/soma/pull/72#discussion_r247348526)

**Comment by Qwaz** [comment]
Closed by #73
