### ISSUE TITLE
Refactor module structures

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#92]
RepositoryManager's module name (`repo::repo_manager::RepositoryManager`) is way to verbose. We can make it shorter by removing redundant `repo_` prefix (i.e. `repo::manager::RepositoryManager`).

Also consider moving some structs like `Manifest` and `SolidManifest` in `soma::repo` to `soma::repo::problem` or `soma::problem`.

**Comment by Qwaz** [comment]
Note that `repo` re-exports `RepositoryManager`, so it is possible to write `soma::repo::RepositoryManager`.

**Comment by Qwaz** [comment]
I'm thinking about something like this.
```
soma
├ repo
│ ├ manager
│ ├ repository
│ └ problem
└ manifest
   ├ manifest
   └ binary_config
```
