### ISSUE TITLE
Use Path(Buf) instead of String when manipulating Path

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#98]
We decided to use String in some cases (like target_path of FileEntry) as Path is displayed differently per platform. However, manipulating path without an aid of Path(i.e. well tested and verified code) may result in an unexpected bug.

I suggest to use Path when Soma needs to manipulate it, and try to use [path-slash](https://crates.io/crates/path-slash) crate to display it.

**Comment by Qwaz** [comment]
Related #53, #44

**Comment by Qwaz** [comment]
Converting backslash path to slash path can cause a problem on Windows depends on the use case. For instance, [extended-path length](https://docs.microsoft.com/ko-kr/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation) only supports backslash as a delimiter.

**Comment by KSAlpha** [comment]
Yes, you are right. It is not a perfect solution to use slash path in all of the path related variables. But, I am sure that using slash path only in `target_path` (i.e displaying unix-understandable-path in windows platform) will not cause such problem.

When #80 is resolved, all copy instructions will be folded into `COPY build/ /` or `ADD build/ /` and this will prevent `path` of `COPY {path} {target_path}` making errors.

**Comment by Qwaz** [comment]
> When #80 is resolved, all copy instructions will be folded into `COPY build/ /` or `ADD build/ /`

I thought it would be `COPY build/ { work_dir }`?

**Comment by KSAlpha** [comment]
> I thought it would be COPY build/ { work_dir }? (or maybe another configurable variable)

It is `COPY build/ /` as the `build` directory will match to the root(/) of the image.
For example, the files going into `/home/prob_name` will be copied into `build/home/prob_name` and will be properly added into `/home/prob_name` of the image.

**Comment by Qwaz** [comment]
I know what `build` directory will look like if we choose to use `COPY build/ /`. What is not described is why the build directory matches the root(/) of the image instead of the project home(/home/prob_name).

**Comment by Qwaz** [comment]
I think the main confusion comes from the role of the working directory. I thought we do not support (or even prevent) putting files outside of the working directory.
